### ISSUE TITLE
Clicking on quest items in the Objectives list

### ISSUE THREAD

**Issue by GitMestra** [NumyAddon/DialogKey_Numy#2] opened 2024-09-16 09:07 UTC
When I try to use a quest item in the Objectives list I get the basic DialogKey_Numy protection violation dialog. Including trying to use the Drop Totem button in the Waterworks Delve.

I am aware that this error often names the wrong addon, but it is pretty consistent behaviour. If DialogKey is disabled, it doesn't occur, and vice versa.

I have been free of these for weeks until I installed DialogKey. Disable it, and all works.

**Comment by Numynum** [comment] 2024-09-16 09:09
got anything that consistently reproduces this, to make it easier for me to find and test a fix? 🙂

**Comment by GitMestra** [comment] 2024-09-16 09:13
It was the Patrol Torch from the Hallowfall weekly and also the gun is shoot the harvesters, but I'll will check Waterworks in a sec.

**Comment by Numynum** [comment] 2024-09-16 09:24
no, I mean more doing \<something\>, then trying to use a quest/Drop Totem button breaks

because I could do a few delves with it working fine, and then after reloading it works fine again

**Comment by Numynum** [comment] 2024-09-16 09:28
I have a theory it might be caused by how gossip/dialog frames are handled, I'll try rework that tonight to see if that helps

**Comment by GitMestra** [comment] 2024-09-16 09:48
Just tried Waterworks - no issue although it did happen while in a group early in the week.

Sporadic Growth weekly. Spawns lesser keyflame 64 30.

Using torch from list gives Blocked. Using from bags doesn't.

/reload it now works.

https://imgur.com/a/bcuRn67

**Comment by GitMestra** [comment] 2024-09-16 10:11
4x [ADDON_ACTION_FORBIDDEN] AddOn 'DialogKey_Numy' tried to call the protected function 'UseQuestLogSpecialItem()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `UseQuestLogSpecialItem'
[string "@Blizzard_ObjectiveTracker/Blizzard_ObjectiveTrackerShared.lua"]:94: in function <...ObjectiveTracker/Blizzard_ObjectiveTrackerShared.lua:87>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
}

**Comment by GitMestra** [comment] 2024-09-16 10:13
4x [ADDON_ACTION_BLOCKED] AddOn 'DialogKey_Numy' tried to call the protected function 'Button:SetPassThroughButtons()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `SetPassThroughButtons'
[string "@Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua"]:224: in function `CheckMouseButtonPassthrough'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:209: in function `AcquirePin'
[string "@Blizzard_SharedMapDataProviders/BonusObjectiveDataProvider.lua"]:97: in function <...haredMapDataProviders/BonusObjectiveDataProvider.lua:92>
[string "=[C]"]: in function `xpcall'
[string "@Blizzard_ObjectAPI/Mainline/AsyncCallbackSystem.lua"]:76: in function `FireCallbacks'
[string "@Blizzard_ObjectAPI/Mainline/AsyncCallbackSystem.lua"]:35: in function <.../Blizzard_ObjectAPI/Mainline/AsyncCallbackSystem.lua:31>
[string "=[C]"]: in function `accessor'
[string "@Blizzard_ObjectAPI/Mainline/AsyncCallbackSystem.lua"]:52: in function `AddCallback'
[string "@Blizzard_ObjectAPI/Mainline/AsyncCallbackSystem.lua"]:60: in function `AddCancelableCallback'
[string "@Blizzard_SharedMapDataProviders/BonusObjectiveDataProvider.lua"]:92: in function `RefreshAllData'
[string "@Blizzard_SharedMapDataProviders/BonusObjectiveDataProvider.lua"]:65: in function `OnEvent'
[string "@Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua"]:99: in function `SignalEvent'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:106: in function <...aceBlizzard_MapCanvas/Blizzard_MapCanvas.lua:105>
[string "=[C]"]: in function `secureexecuterange'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:109: in function `OnEvent'
[string "@Blizzard_WorldMap/Blizzard_WorldMap.lua"]:148: in function <...rfaceBlizzard_WorldMap/Blizzard_WorldMap.lua:147>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
}

**Comment by GitMestra** [comment] 2024-09-16 11:00
I brought down another alt. No problems until I picked a second quest up. Now both fail. 

I can try the fix you give, but I really have no idea how to replicate to test.

**Comment by Numynum** [comment] 2024-09-16 11:07
I'd suggest just giving it a try, and if it doesn't break after like an hour of play, I'd call that a win
I don't have time to look into it until tonight (EU), or maybe even until tomorrow

**Comment by GitMestra** [comment] 2024-09-16 11:21
OK. Not urgent, I can reload to work around it, and like most of these things it is hard to make happen when you want it to.

I tried dropping quests and picking up again until I checked after getting a dynamic quest.

Commented out your suggestion and testing again.

**Comment by Numynum** [comment] 2024-09-16 11:23
cool, would appreciate knowing if it no longer happens after a couple of hours of playing ^^

**Comment by Numynum** [comment] 2024-09-16 16:31
actually, can you also install the Ace3 addon? https://www.curseforge.com/wow/addons/ace3
if it then starts blaming Ace3 rather than DialogKey, there's a decent chance some other addon is at fault

**Comment by Numynum** [comment] 2024-09-16 17:53
https://github.com/NumyAddon/DialogKey_Numy/releases/tag/v1.1.2-beta might help, but I'm not sure, since I couldn't reproduce the problem just now 😕

**Comment by GitMestra** [comment] 2024-09-17 00:49
I did a short test with the commented-out line, but didn't see anything - except for the removal of gossip numbers. I don't think the error is NPC chat though. The 2 bugsack dumps are possibly not related. 

I will give the beta a go. I already run Ace since mid-DF when this last happened with multiple addons. I know the blocking error can be wrongly assigned because of common libraries.

**Comment by GitMestra** [comment] 2024-09-17 01:22
Running beta and still occurs. Brought new toon to Hallowfall light area.

Did some mining/herb on the way (none of others were). Did the kill 60 plants dynamic quest to get some shards to spawn the quest givers.

Got the Sporadic Growth quest. Tried using the torch - blocked. Bugsack only reports on error - UseQuestLogSpecialItem.

I tried "/cast patrol torch" and got the same error assigned to Prat:
1x [ADDON_ACTION_FORBIDDEN] AddOn 'Prat-3.0-3.9.58' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `UseItemByName'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:1228: in function `SecureCmdUseItem'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:1261: in function `?'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5459: in function <Blizzard_ChatFrameBase/Mainline/ChatFrame.lua:5425>
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5131: in function <Blizzard_ChatFrameBase/Mainline/ChatFrame.lua:5130>
[string "=[C]"]: ?
[string "=[C]"]: in function `ChatEdit_SendText'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5167: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:140_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:140_OnEnterPressed"]:1>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
}

**Comment by Numynum** [comment] 2024-09-17 06:30
Can you try playing with taintlog enabled (https://warcraft.wiki.gg/wiki/CVar_taintLog), and commenting out the same line again (so the numbers don't show) 

I'm not sure what it could possibly be other than the npc dialogs, everything else should be safe as far as I can tell..

Taintlog can be a bit weird, but general it works fine if you do this
1. /console taintLog 2
2. /reload
3. play until you get the error
4. /console taintLog 0
5. /reload
6. upload the file here and go back to step 1

**Comment by Numynum** [comment] 2024-09-17 06:32
Unfortunately the errors from bugsack aren't really helpful in figuring out the actual cause of the issue :/

**Comment by GitMestra** [comment] 2024-09-17 06:53
Will give it a go tomorrow when there are a lot of new quests.

**Comment by GitMestra** [comment] 2024-09-18 01:53
I commented out the line and did the taintlog. Did all sorts of content. Lots of lamplight stuff (inc objective list quest items) and didn't get an Block for DialogKey.

I did get an Ace3 error. I think that's when I was moving Baganator categories when I went into combat. 

Added taintlog
[taint.zip](https://github.com/user-attachments/files/17037297/taint.zip)

Did you want me to try it with the line active?

**Comment by Numynum** [comment] 2024-09-18 04:10
If you could get a taintlog from the beta version (with the line active), that'd be cool
you already confirmed the beta still had issues right?

**Comment by GitMestra** [comment] 2024-09-18 04:21
I will do it on alt in a few to grab quests that I did already. Many of the Lamplight stuff has quest objects to use. Also just did Black Temple and a bunch of addons errored so it's a bit noisy.

**Comment by GitMestra** [comment] 2024-09-18 05:22
Turned on line. Ran all sorts of stuff. No errors till I got to Lamplighter area.

[taint.zip](https://github.com/user-attachments/files/17038759/taint.zip)

I could see the error on Bugsack before trying to use an item. When I did try I got the Block warning.

**Comment by GitMestra** [comment] 2024-09-18 05:33
And another. Restarted client and deleted previous log.

[taint (2).zip](https://github.com/user-attachments/files/17038846/taint.2.zip)

**Comment by Numynum** [comment] 2024-09-18 12:51
I've pretty much rewritten all of the internal "click" logic, to use secure clicks, and changed once again how adding the numbers to the dialog options is handled
would appreciate it if you'd check out the new beta 🙂 https://github.com/NumyAddon/DialogKey_Numy/releases/tag/v1.2.0-beta

**Comment by Numynum** [comment] 2024-09-18 13:29
hm probably not, there doesn't seem to be anything interesting in there sadly

**Comment by GitMestra** [comment] 2024-09-19 03:05
Ran 2 alts through a lot of world content: weeklies, dailies, and world quests. Interacting with NPCs and using quest items. 

Nothing to report - so, good news. 

The only error I experienced was when Bartender decided to do something when I gained a level in combat.

I will, of course, report again if I have news.

**Comment by Numynum** [comment] 2024-09-19 09:52
thanks for your help with testing things, it led to the addon getting much better overall 🙂 

I'll close this issue for now, with the hope/assumption that it's fully fixed with the latest version (though frankly if it's not, then I don't really know what else there's left to try, I don't see _anything_ left in the code that I'd consider risky now ^^)

feel free to comment here again if it comes back, or open another issue if there's anything else or suggestions/requests ^^

**Closed by Numynum** 2024-09-19 09:52 UTC
